import { Nunito_Sans } from "next/font/google";
import styles from "./page.module.css";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.className}`}>
        <nav className={styles.nav}>
          <button type="button" className={styles.menuBtn}>
            <img src="/images/menu.png" alt="burger menu" />
          </button>
          <div className={styles.logo}>Tripma</div>
        </nav>
        {children}
      </body>
    </html>
  );
}
