import { Nunito_Sans } from "next/font/google";
import "@/app/globals.css";
import NextAuthProvider from "@/providers/NextAuthProvider";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.className}`}><NextAuthProvider>{children}</NextAuthProvider></body>
    </html>
  );
}
